#!/bin/bash

set -e

go run main.go 10 Static 6 [] Fixed
python3 graph.py 10 Static 6 [] Fixed

go run main.go 10 Seasonal 6 [] Fixed
python3 graph.py 10 Seasonal 6 [] Fixed

go run main.go 10 Extreme 6 [] Fixed
python3 graph.py 10 Extreme 6 [] Fixed